/* Alpha OS — vues « intelligence » : conseil des six, décisions, cône, archive, veille, réglages (français) */
(function (root) {
  "use strict";
  const AOS = (root.AOS = root.AOS || {});
  const { isNum, fmt, clamp, stats } = AOS.util;
  const T = AOS.i18n, D = AOS.dom;
  const { html, raw, set, sum, $, usd, usdS, pct, px, tag, prov, lvlTag, sideTag, kv, more, list, json, esc, ring } = D;
  const V = {};

  // ---- CONSEIL DES SIX -----------------------------------------------------------------------------
  V.council = function (a) {
    const ag = a.agents, o = a.orchestration, rep = a.reputation;
    const order = ["ORACLE", "FLOW", "EDGE", "ALLOCATOR", "SENTINEL", "ARCHIVE"];
    const dirTag = (d) => tag(T.dir(d), d === "bullish" ? "long" : d === "bearish" ? "short" : "");
    set($("#council-body"), html`
      <div class="agents">${raw(order.map((n) => { const x = ag[n], r = rep.agents[n], meta = T.agent(n); return html`<div class="card agent">
        <div class="avatar" style="background:${meta.color}">${meta.glyph}</div>
        <div><div class="name">${meta.name} ${x.veto ? tag("VETO", "crit") : ""}</div><div class="role">${meta.role}</div></div>
        <div class="say"><b>${n === "SENTINEL" ? T.level(x.level) : T.dir(x.direction)}</b> — ${T.rec(x.recommendation)}${x.signals[0] ? html`<br/><span class="dimc">${x.signals[0]}</span>` : ""}</div>
        ${more("Ses arguments", raw(`${list(x.signals.slice(0, 4)).s}${x.risks?.length ? `<div class="hint" style="margin-top:6px"><b>Risques</b></div>${list(x.risks.slice(0, 3)).s}` : ""}${x.invalidation?.length ? `<div class="hint" style="margin-top:6px"><b>Ce qui le ferait changer d'avis</b></div>${list(x.invalidation.slice(0, 3)).s}` : ""}<div class="hint" style="margin-top:8px">Confiance ${Math.round(x.confidence * 100)} % · horizon ${esc(x.time_horizon)} · taille conseillée ×${isNum(x.position_size_modifier) ? x.position_size_modifier.toFixed(2) : "—"} · réputation : ${r.n} appels résolus${r.n ? `, précision ${esc(fmt.pct(r.accuracy, 0))}, poids ×${r.multiplier.toFixed(2)}` : ", poids ×1,00 (a priori)"} ${prov(x.prov).s}</div>`))}
        ${more("Sortie structurée (JSON)", json({ ...x, votes: undefined, heatmap: undefined, oiStress: undefined, opportunities: x.opportunities?.map((q) => q.id), rejected: x.rejected?.map((q) => q.id), reviews: x.reviews?.map((q) => q.id), reputation: undefined, calibration: undefined, edgeDecay: undefined, regime: undefined, temperature: undefined }))}
      </div>`.s; }).join(""))}</div>
      <div class="card" style="margin-top:12px">
        <div class="rowring">${ring(100 - o.marketDisagreement * 100, "accord", "var(--info)")}<div><div class="big" style="font-size:18px">Désaccord du conseil : ${fmt.pct(o.marketDisagreement, 0)}</div><div class="sub2">Un conseil unanime n'a pas la même valeur qu'un conseil divisé : plus le désaccord monte, plus la taille des positions baisse.</div></div></div>
        ${more("Conviction par actif", raw(`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Actif</th><th class="r">Long</th><th class="r">Short</th><th class="r">Désaccord</th><th>Votes (sens · confiance · poids)</th></tr></thead><tbody>${Object.values(o.convictions).map((c) => `<tr><td class="t"><b>${esc(c.coin)}</b></td><td class="r ${c.long >= 60 ? "pos" : ""}">${c.long}</td><td class="r ${c.short >= 60 ? "neg" : ""}">${c.short}</td><td class="r ${c.disagreement > 0.5 ? "warnc" : ""}">${Math.round(c.disagreement * 100)} %</td><td class="t" style="white-space:normal;font-size:11px">${c.parts.map((p) => `<span class="tag ${p.dir > 0.15 ? "long" : p.dir < -0.15 ? "short" : ""}">${esc(T.agent(p.agent).name)} ${p.dir > 0 ? "+" : ""}${p.dir.toFixed(2)} · ${Math.round(p.confidence * 100)} % · ${(p.weight * 100).toFixed(0)}</span>`).join(" ")}</td></tr>`).join("")}</tbody></table></div><div class="hint">Score = Σ poids × réputation × sens × confiance. Poids de base : marché/quant 40 % (Oracle 20 + Chasseur 20), flux 35 %, contexte 25 % (Allocateur 15 + Archive 10). La Sentinelle ne vote pas : elle oppose son veto.</div>`))}
        ${more("Tableau des scores (réputation mesurée)", raw(`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Agent</th><th class="r">Appels</th><th class="r">Précision</th><th class="r">Récent (20)</th><th class="r">Brier</th><th class="r">Faux positifs</th><th class="r">Poids effectif</th></tr></thead><tbody>${order.filter((n) => n !== "SENTINEL").map((n) => { const r = rep.agents[n]; return `<tr><td class="t"><b>${esc(T.agent(n).name)}</b></td><td class="r">${r.n}<span class="dimc">${r.pending ? " +" + r.pending + " en cours" : ""}</span></td><td class="r">${esc(fmt.pct(r.accuracy, 0))}</td><td class="r">${esc(fmt.pct(r.accuracyRecent, 0))}</td><td class="r">${isNum(r.brier) ? r.brier.toFixed(3) : "—"}</td><td class="r">${r.falsePositives}</td><td class="r">${(o.effectiveWeights[n] * 100).toFixed(0)} %</td></tr>`; }).join("")}<tr><td class="t"><b>SENTINELLE</b></td><td class="r" colspan="5">${rep.avoided.sentinelN} vetos résolus · pertes évitées <span data-private>${esc(fmt.usd(rep.avoided.sentinelAvoided))}</span> · ${a.orchestration.cards.filter((c) => c.status !== "APPROVED").length} trade(s) refusé(s) aujourd'hui</td><td class="r">veto</td></tr></tbody></table></div><div class="hint">Un appel = un sens + une probabilité, résolu à l'horizon de l'agent (Oracle 7 j, Flux 2 j, Chasseur 4 j) sur la clôture horaire. Le poids converge vers la performance après ~20 appels. Décisions IGNORER/VETO résolues : ${rep.avoided.n} · pertes évitées <span data-private>${esc(fmt.usd(rep.avoided.lossesAvoided))}</span> · gains manqués <span data-private>${esc(fmt.usd(rep.avoided.gainsMissed))}</span>.</div>`))}
      </div>`);
    sum("council", `désaccord ${fmt.pct(o.marketDisagreement, 0)} · BTC ${o.convictions.BTC?.long ?? "—"}/100 long`);
  };

  // ---- DÉCISIONS ------------------------------------------------------------------------------------
  V.decisions = function (a) {
    const o = a.orchestration;
    if (!o.cards.length) {
      set($("#decisions-body"), html`<div class="perfect"><div class="medal">🏅</div><div><div class="big" style="font-size:18px">Aucun trade — décision parfaite</div><div class="sub2">Aucune configuration avec un avantage suffisant après coûts sur ${Object.keys(a.features.byCoin).filter((c) => a.features.byCoin[c].h4).length} actifs scannés. Ne rien faire est une décision, et aujourd'hui c'est la bonne.</div>${a.agents.EDGE.rejected.length ? more("Configurations refusées par le Chasseur", list(a.agents.EDGE.rejected.map((r) => `${r.coin} ${r.side} ${r.name} : ${r.rejectReason}`))) : ""}</div></div>`);
      sum("decisions", "aucun trade");
      return;
    }
    set($("#decisions-body"), raw(o.cards.map((c) => {
      const st = c.status, sz = c.sizing;
      return html`<div class="card decision ${st === "APPROVED" ? "lift" : ""}" data-card="${c.id}"><span class="stripe ${st === "APPROVED" ? "NORMAL" : st === "VETO" ? "CRITICAL" : "WATCH"}"></span>
        <div class="head"><span class="sym">${c.coin}</span>${sideTag(c.side)}<span class="tag">${c.name}</span>${tag(st === "APPROVED" ? "Sentinelle : approuvé" : st === "VETO" ? "Sentinelle : VETO" : "Contrôle : refusé", st === "APPROVED" ? "ok" : st === "VETO" ? "crit" : "warn")}<span style="margin-left:auto">${ring(c.conviction, "conviction", st === "APPROVED" ? "var(--ok)" : "var(--warn)")}</span></div>
        <div class="levels"><div><div class="k">Entrée</div><div class="v">${px(c.entry)}</div></div><div><div class="k">Invalidation</div><div class="v neg">${px(c.invalidation)}</div></div><div><div class="k">Objectif</div><div class="v pos">${px(c.target)}</div></div></div>
        <div class="facts">${tag(`espérance ${c.evR >= 0 ? "+" : ""}${c.evR.toFixed(2)}R`, c.evR > 0 ? "ok" : "bad")}${tag(`risque/gain ${c.rr.toFixed(1)}`)}${tag(`p ${Math.round(c.pRange[0] * 100)}–${Math.round(c.pRange[1] * 100)} % · incertitude ${T.unc(c.uncertainty)}`)}${tag(`régime : ${T.regime(c.regime)}`)}${tag(`flux : ${c.flowDir > 0.15 ? "favorable" : c.flowDir < -0.15 ? "défavorable" : "neutre"}`)}${tag(`portefeuille : ${c.portfolioImpact === "Positive" ? "amélioré" : c.portfolioImpact === "Negative" ? "dégradé" : "neutre"}`)}${tag(`funding : ${c.fundingLabel === "Cost" ? "coût" : c.fundingLabel === "Tailwind" ? "favorable" : "neutre"}`)}${sz ? tag(`taille ${fmt.qty(sz.qty)} · mise en risque ${fmt.usd(sz.riskUsd)}`, "accent") : ""}</div>
        <div class="gates">${raw(c.gate.gates.map((g) => `<span class="g ${g.pass ? "pass" : "fail"}" title="${esc(g.detail)}">${esc(T.gate(g.name))} ${g.pass ? "✓" : "✕"}</span>`).join(""))}</div>
        <div class="actions"><button class="btn primary" data-act="EXECUTE" ${st !== "APPROVED" ? "disabled" : ""}>EXÉCUTER</button><button class="btn" data-act="SIMULATE">SIMULER</button><button class="btn ghost" data-act="IGNORE">IGNORER</button></div>
        ${more("Pourquoi ?", raw(`<b>${esc(c.why)}</b>${list(c.convictionParts.map((p) => `${T.agent(p.agent).name} (${p.dir > 0 ? "+" : ""}${p.dir.toFixed(2)}) : ${p.reasons[0] || ""}`)).s}<div class="hint" style="margin-top:8px">Invalidation : ${esc(c.invalidationWhy)} · objectif : ${esc(c.targetWhy)} · objectif 2 ${esc(fmt.px(c.target2))} · objectif 3 ${esc(fmt.px(c.target3))} · horizon ${c.horizonDays} j</div><div class="hint">Probabilité : a priori ${esc(AOS.agents.EDGE.PRIORS[c.type] * 100)} % ${esc(c.pAdjustments.join(" · "))} · espérance avant coûts ${c.evRBeforeCosts.toFixed(2)}R · coûts ${c.costR.toFixed(2)}R (frais ${(c.feePct * 100).toFixed(3)} % + funding ${(c.fundingCostPct * 100).toFixed(3)} %) · poids d'usure ×${c.decayWeight.toFixed(2)}</div>`))}
        ${more("Les 7 contrôles et la taille", raw(`<div class="tbl-wrap"><table class="tbl"><tbody>${c.gate.gates.map((g) => `<tr><td class="t ${g.pass ? "pos" : "neg"}">${esc(T.gate(g.name))}</td><td class="t" style="white-space:normal">${esc(g.detail)}</td></tr>`).join("")}</tbody></table></div>${sz ? `<div class="hint" style="margin-top:8px">Taille : ${esc(sz.why)} · Kelly plein ${(sz.kelly.full * 100).toFixed(1)} % (jamais utilisé) · 0,10 K ${esc(fmt.usd(sz.kellyRiskUsd.k10))} · 0,25 K ${esc(fmt.usd(sz.kellyRiskUsd.k25))} · 0,50 K ${esc(fmt.usd(sz.kellyRiskUsd.k50))} · retenu : ${esc(sz.chosen === "Risk budget" ? "budget de risque" : sz.chosen)}</div>` : ""}${c.gate.impact ? `<div class="mini" style="margin-top:8px"><div class="m"><div class="k">Δ rendement attendu</div><div class="v" data-private>${esc(fmt.usdSigned(c.gate.impact.deltas.expectedReturn))}</div></div><div class="m"><div class="k">Δ CVaR 95 % 1 j</div><div class="v" data-private>${esc(fmt.usdSigned(c.gate.impact.deltas.cvar))}</div></div><div class="m"><div class="k">Δ distance liquidation</div><div class="v">${esc(fmt.pct(c.gate.impact.deltas.liqRisk, 1, true))}</div></div><div class="m"><div class="k">Δ funding /j</div><div class="v" data-private>${esc(fmt.usdSigned(c.gate.impact.deltas.funding, 2))}</div></div><div class="m"><div class="k">Δ corrélation</div><div class="v">${c.gate.impact.deltas.correlation.toFixed(3)}</div></div><div class="m"><div class="k">Δ exposition nette</div><div class="v" data-private>${esc(fmt.usdSigned(c.gate.impact.deltas.netExposure))}</div></div><div class="m"><div class="k">Δ perte au choc</div><div class="v" data-private>${esc(fmt.usdSigned(c.gate.impact.deltas.stressLoss))}</div></div><div class="m"><div class="k">Niveau après</div><div class="v lvl-${esc(c.gate.impact.newLevel)}">${esc(T.level(c.gate.impact.newLevel))}</div></div></div>` : ""}`))}
        ${c.review ? more(`Équipe rouge (${c.review.redTeam.verdict === "PASS" ? "rien de bloquant" : c.review.redTeam.verdict === "CAUTION" ? "prudence" : "rejet"}) et pré-mortem`, raw(`${list(c.review.redTeam.findings.filter((f) => f.severity > 0).map((f) => f.text)).s}<div class="hint" style="margin-top:8px"><b>Pré-mortem — si ce trade perd fort, la cause la plus probable :</b></div>${list(c.review.preMortem).s}`)) : ""}
      </div>`.s;
    }).join("")));
    sum("decisions", `${o.approved.length} approuvée${o.approved.length > 1 ? "s" : ""} · ${o.cards.length - o.approved.length} refusée${o.cards.length - o.approved.length > 1 ? "s" : ""}`);
  };

  // ---- CÔNE ----------------------------------------------------------------------------------------
  V.cone = function (a) {
    const c = a.cone, body = $("#cone-body");
    if (!c.ok) { set(body, html`<div class="empty">Cône indisponible : ${c.reason}</div>`); sum("cone", "—"); return; }
    const h90 = c.horizons[c.horizons.length - 1];
    set(body, html`<div class="card"><h3>Où peut être mon equity ${prov(c.prov)} <span class="tag">${c.paths} trajectoires</span></h3>
      <canvas id="cone-canvas" class="chart" width="800" height="300"></canvas>
      <div class="legend"><span><i style="background:rgba(200,178,131,.18)"></i>P10–P90</span><span><i style="background:rgba(200,178,131,.4)"></i>P25–P75</span><span><i style="background:#c8b283"></i>médiane</span><span><i style="background:#ff3d5a"></i>liquidation</span></div>
      <div class="mini" style="margin-top:10px">${raw(c.horizons.map((h) => `<div class="m"><div class="k">${h.horizon} jour${h.horizon > 1 ? "s" : ""}</div><div class="v" data-private>${esc(fmt.usd(h.p50))}</div><div class="hint"><span data-private>${esc(fmt.usd(h.p10))} → ${esc(fmt.usd(h.p90))}</span><br/>liquidation <b class="${h.pLiq > 0.1 ? "neg" : h.pLiq > 0.02 ? "warnc" : ""}">${esc(fmt.pct(h.pLiq, 1))}</b></div></div>`).join(""))}</div>
      ${more("Tableau complet", raw(`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Horizon</th><th class="r">P10</th><th class="r">P25</th><th class="r">P50</th><th class="r">P75</th><th class="r">P90</th><th class="r">P(perte)</th><th class="r">P(liquidation)</th></tr></thead><tbody>${c.horizons.map((h) => `<tr><td class="t">${h.horizon} j</td><td class="r neg" data-private>${esc(fmt.usd(h.p10))}</td><td class="r" data-private>${esc(fmt.usd(h.p25))}</td><td class="r" data-private><b>${esc(fmt.usd(h.p50))}</b></td><td class="r" data-private>${esc(fmt.usd(h.p75))}</td><td class="r pos" data-private>${esc(fmt.usd(h.p90))}</td><td class="r">${esc(fmt.pct(h.pLoss, 0))}</td><td class="r">${esc(fmt.pct(h.pLiq, 1))}</td></tr>`).join("")}</tbody></table></div><div class="hint">${esc(c.note)} La probabilité de liquidation suppose des positions inchangées : c'est le coût de l'inaction, pas une prévision.</div>`))}</div>`);
    const cv = $("#cone-canvas"), ctx = cv.getContext("2d");
    const W = cv.width, H = cv.height, padL = 64, padR = 16, padT = 14, padB = 28;
    const pts = [{ horizon: 0, p10: c.equity0, p25: c.equity0, p50: c.equity0, p75: c.equity0, p90: c.equity0 }, ...c.horizons];
    const maxH = Math.max(...c.horizons.map((h) => h.horizon));
    const lo = Math.min(...pts.map((p) => p.p10)) * 0.95, hi = Math.max(...pts.map((p) => p.p90)) * 1.03;
    const X = (h) => padL + Math.sqrt(h / maxH) * (W - padL - padR), Y = (v) => padT + (1 - (v - lo) / (hi - lo)) * (H - padT - padB);
    ctx.clearRect(0, 0, W, H);
    ctx.strokeStyle = "rgba(196,208,232,.1)"; ctx.fillStyle = "#8b93a7"; ctx.font = "11px JetBrains Mono, monospace"; ctx.textAlign = "right";
    for (let i = 0; i <= 4; i++) { const v = lo + (hi - lo) * i / 4; ctx.beginPath(); ctx.moveTo(padL, Y(v)); ctx.lineTo(W - padR, Y(v)); ctx.stroke(); ctx.fillText(document.body.classList.contains("privacy") ? "•••" : fmt.usd(v), padL - 6, Y(v) + 4); }
    ctx.textAlign = "center"; for (const h of c.horizons) ctx.fillText(h.horizon + " j", X(h.horizon), H - 8);
    const band = (kLo, kHi, col) => { ctx.beginPath(); pts.forEach((p, i) => (i ? ctx.lineTo(X(p.horizon), Y(p[kLo])) : ctx.moveTo(X(p.horizon), Y(p[kLo])))); [...pts].reverse().forEach((p) => ctx.lineTo(X(p.horizon), Y(p[kHi]))); ctx.closePath(); ctx.fillStyle = col; ctx.fill(); };
    band("p10", "p90", "rgba(200,178,131,.16)"); band("p25", "p75", "rgba(200,178,131,.3)");
    ctx.beginPath(); pts.forEach((p, i) => (i ? ctx.lineTo(X(p.horizon), Y(p.p50)) : ctx.moveTo(X(p.horizon), Y(p.p50)))); ctx.strokeStyle = "#c8b283"; ctx.lineWidth = 2; ctx.stroke();
    ctx.setLineDash([4, 4]); ctx.beginPath(); ctx.moveTo(padL, Y(c.equity0)); ctx.lineTo(W - padR, Y(c.equity0)); ctx.strokeStyle = "rgba(255,255,255,.35)"; ctx.lineWidth = 1; ctx.stroke(); ctx.setLineDash([]);
    const mm = a.snapshot.account.mm; if (isNum(mm) && mm > lo) { ctx.beginPath(); ctx.moveTo(padL, Y(mm)); ctx.lineTo(W - padR, Y(mm)); ctx.strokeStyle = "rgba(255,61,90,.7)"; ctx.stroke(); }
    sum("cone", `liquidation à 90 j : ${fmt.pct(h90.pLiq, 0)}`);
  };

  // ---- ARCHIVE ---------------------------------------------------------------------------------------
  V.archive = function (a) {
    const al = a.alpha, st = al.stats, rep = a.reputation, w = al.windows;
    const journal = AOS.store.list("journal");
    const winRow = (k, label) => { const x = w[k]; if (x?.note) return `<tr><td class="t">${esc(label)} <span class="dimc">${x.days} j</span></td><td class="r ${x.pnl >= 0 ? "pos" : "neg"}" data-private>${esc(fmt.usdSigned(x.pnl))}</td><td colspan="5" class="t dimc" style="white-space:normal">${esc(x.note)}</td><td class="r">${esc(fmt.pct(x.mdd?.mdd, 1))}</td><td class="r">—</td></tr>`; if (!x || !isNum(x.ret)) return `<tr><td class="t">${esc(label)}</td><td colspan="8" class="t dimc">indisponible</td></tr>`; return `<tr><td class="t">${esc(label)} <span class="dimc">${x.days} j</span></td><td class="r ${x.ret >= 0 ? "pos" : "neg"}">${esc(fmt.pct(x.ret, 1, true))}</td><td class="r">${esc(fmt.pct(x.btc, 1, true))}</td><td class="r">${esc(fmt.pct(x.eth, 1, true))}</td><td class="r">${esc(fmt.pct(x.mix, 1, true))}</td><td class="r ${x.alphaBTC >= 0 ? "pos" : "neg"}"><b>${esc(fmt.pct(x.alphaBTC, 1, true))}</b></td><td class="r">${esc(fmt.pct(x.alphaBTCBeforeCosts, 1, true))}</td><td class="r">${esc(fmt.pct(x.mdd.mdd, 1))}</td><td class="r">${isNum(x.sharpe) ? x.sharpe.toFixed(2) : "—"} / ${isNum(x.sortino) ? x.sortino.toFixed(2) : "—"}</td></tr>`; };
    const m = w.month;
    set($("#archive-body"), html`
      <div class="card accent"><h3>La question qui compte</h3>
        <div class="rowring">${ring(isNum(m?.alphaBTC) ? 50 + clamp(m.alphaBTC * 100, -50, 50) : NaN, "alpha 30 j", isNum(m?.alphaBTC) && m.alphaBTC >= 0 ? "var(--ok)" : "var(--bad)", isNum(m?.alphaBTC) ? fmt.pct(m.alphaBTC, 0, true) : "—")}<div><div class="big" style="font-size:18px">${isNum(m?.alphaBTC) ? (m.alphaBTC >= 0 ? "Sur 30 jours, ton trading a battu BTC." : "Sur 30 jours, tenir du BTC aurait fait mieux.") : "Pas assez d'historique pour répondre."}</div><div class="sub2">${m && isNum(m.ret) ? `Toi ${fmt.pct(m.ret, 1, true)} · BTC ${fmt.pct(m.btc, 1, true)} · ETH ${fmt.pct(m.eth, 1, true)} · ne rien faire 0 %` : ""}${isNum(al.perpsAllTimePnl) ? ` · PnL perps cumulé depuis le début : <b class="${al.perpsAllTimePnl >= 0 ? "pos" : "neg"}" data-private>${fmt.usdSigned(al.perpsAllTimePnl)}</b>` : ""}</div></div></div>
      </div>
      <div class="mini" style="margin-top:12px">
        <div class="m"><div class="k">Trades clos</div><div class="v">${st.n} <small class="dimc">incert. ${T.unc(st.uncertainty)}</small></div></div>
        <div class="m"><div class="k">Taux de réussite · facteur de profit</div><div class="v">${fmt.pct(st.winRate, 0)} · ${isNum(st.profitFactor) ? (st.profitFactor === Infinity ? "∞" : st.profitFactor.toFixed(2)) : "—"}</div></div>
        <div class="m"><div class="k">Espérance par trade</div><div class="v ${st.expectancy >= 0 ? "pos" : "neg"}" data-private>${fmt.usdSigned(st.expectancy)}</div></div>
        <div class="m"><div class="k">Fuite frais + funding</div><div class="v neg" data-private>${fmt.usd(al.leakage.fees90d - al.leakage.funding90d)}</div><div class="hint">frais ${fmt.usd(al.leakage.fees90d)} · funding net ${fmt.usdSigned(al.fundingNet)}</div></div>
      </div>
      <div class="card" style="margin-top:12px">
        ${more("Alpha par fenêtre (toi vs BTC, ETH, mix, ne rien faire)", raw(`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Fenêtre</th><th class="r">Toi</th><th class="r">BTC</th><th class="r">ETH</th><th class="r">Mix 50/50</th><th class="r">Alpha vs BTC</th><th class="r">avant coûts</th><th class="r">Pire baisse</th><th class="r">Sharpe / Sortino</th></tr></thead><tbody>${winRow("week", "7 jours (perps)") + winRow("month", "30 jours (perps)") + winRow("allTime", "Depuis le début (perps)") + winRow("totalMonth", "30 jours (compte total)") + winRow("totalAllTime", "Depuis le début (compte total)")}</tbody></table></div>${isNum(al.capital?.deposits) ? kv("Dépôts · retraits (ledger 365 j)", raw(`<span data-private>${esc(fmt.usd(al.capital.deposits))} · ${esc(fmt.usd(al.capital.withdrawals))}</span>`)).s : ""}<div class="hint">Rendement = Dietz modifié sur l'historique de valeur (séries perps de l'API, dépôts/retraits/transferts neutralisés). Une hausse due seulement au bêta BTC n'est pas de l'alpha. Fills couverts : ${al.activity?.spanDays ? al.activity.spanDays.toFixed(0) + " j (" + al.fillsCount + " fills" + (al.activity.truncatedWindow ? ", fenêtre tronquée" : "") + ")" : "aucun"} ; ${al.truncatedCount} trade(s) commencé(s) avant la fenêtre exclus.</div>`), true)}
        ${al.attribution ? more("D'où vient le PnL des 30 derniers jours ?", raw(`<div class="tbl-wrap"><table class="tbl"><tbody>${al.attribution.map((r) => `<tr><td class="t">${esc(r.name)}</td><td class="r ${r.value >= 0 ? "pos" : "neg"}" data-private>${esc(fmt.usdSigned(r.value))}</td><td class="t dimc">${esc(r.note)} ${prov(r.prov).s}</td></tr>`).join("")}</tbody></table></div>`)) : ""}
        ${more("PnL par actif, par sens, par régime", raw(`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Clé</th><th class="r">n</th><th class="r">Réussite</th><th class="r">Net</th></tr></thead><tbody>${[...st.byAsset, ...st.bySide, ...st.byRegime.filter((r) => r.key !== "UNKNOWN")].map((r) => `<tr><td class="t">${esc(T.regime(r.key) !== r.key ? T.regime(r.key) : r.key)}</td><td class="r">${r.n}</td><td class="r">${esc(fmt.pct(r.winRate, 0))}</td><td class="r ${r.net >= 0 ? "pos" : "neg"}" data-private>${esc(fmt.usdSigned(r.net))}</td></tr>`).join("") || '<tr><td colspan="4" class="empty">Aucun trade clos</td></tr>'}</tbody></table></div>${al.patterns.length ? `<div class="hint" style="margin-top:8px"><b>Schémas (n ≥ 5)</b></div>${list(al.patterns).s}` : '<div class="hint" style="margin-top:8px">Il faut au moins 5 trades par catégorie pour conclure.</div>'}`))}
        ${more("Et si j'avais tenu ? (contrefactuels)", raw(`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Trade</th><th class="r">Réel</th><th class="r">Tenu</th><th class="r">Meilleur gain</th><th class="r">Pire excursion</th><th class="r">BTC</th></tr></thead><tbody>${al.counterfactuals.slice(-12).reverse().map((c) => `<tr><td class="t">${esc(c.coin)} ${esc(c.side)} <span class="dimc">${esc(fmt.date(c.openTs))}${c.regime ? " · " + esc(T.regime(c.regime)) : ""}</span></td><td class="r ${c.actual >= 0 ? "pos" : "neg"}" data-private>${esc(fmt.usdSigned(c.actual))}</td><td class="r" data-private>${esc(fmt.usdSigned(c.hold))}</td><td class="r" data-private>${esc(fmt.usdSigned(c.mfe))}</td><td class="r" data-private>${esc(fmt.usdSigned(c.mae))}</td><td class="r" data-private>${esc(fmt.usdSigned(c.btc))}</td></tr>`).join("") || '<tr><td colspan="6" class="empty">Aucun trade clos dans la fenêtre horaire (30 j)</td></tr>'}</tbody></table></div><div class="hint">Sert à améliorer les règles, pas à regretter.</div>`))}
        ${more("Calibration et usure des configurations", raw(`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>p prédite</th><th class="r">n</th><th class="r">prédit</th><th class="r">réalisé</th></tr></thead><tbody>${rep.calibration.bins.map((b) => `<tr><td class="t">${Math.round(b.lo * 100)}–${Math.round(b.hi * 100)} %</td><td class="r">${b.n}</td><td class="r">${esc(fmt.pct(b.predicted, 0))}</td><td class="r ${isNum(b.realized) && isNum(b.predicted) && b.realized < b.predicted - 0.1 ? "neg" : ""}">${esc(fmt.pct(b.realized, 0))}</td></tr>`).join("")}</tbody></table></div><div class="hint">Brier global ${isNum(rep.calibration.brier) ? rep.calibration.brier.toFixed(3) : "—"} sur ${rep.calibration.n} décisions résolues. Les probabilités se recalibrent automatiquement à partir de 30 décisions par type.</div><div class="tbl-wrap"><table class="tbl"><thead><tr><th>Configuration</th><th class="r">n</th><th class="r">R moyen (30)</th><th class="r">R moyen (90)</th><th class="r">Poids</th></tr></thead><tbody>${Object.entries(rep.edgeDecay).map(([k, v]) => `<tr><td class="t">${esc(T.setup(k))} ${v.decaying ? '<span class="tag bad">USURE</span>' : ""}</td><td class="r">${v.n}</td><td class="r">${isNum(v.rolling30) ? v.rolling30.toFixed(2) : "—"}</td><td class="r">${isNum(v.rolling90) ? v.rolling90.toFixed(2) : "—"}</td><td class="r">×${v.weight.toFixed(2)}</td></tr>`).join("") || '<tr><td colspan="5" class="empty">Aucune décision résolue</td></tr>'}</tbody></table></div>`))}
      </div>
      <div class="card" style="margin-top:12px"><h3>Journal</h3>
        <div class="form c2"><div class="field"><label>Sujet</label><input id="j-title" placeholder="ex. BTC long — pourquoi je garde"/></div><div class="field"><label>Type</label><select id="j-type"><option>THÈSE</option><option>ENTRÉE</option><option>SORTIE</option><option>RENFORT</option><option>COUVERTURE</option><option>AUCUN TRADE</option><option>ERREUR</option></select></div></div>
        <div class="field" style="margin-top:8px"><label>Note (hypothèse, raison de sortie, leçon)</label><textarea id="j-note"></textarea></div>
        <div style="display:flex;gap:8px;margin-top:8px;align-items:center"><button class="btn primary" id="j-add" style="flex:0 0 auto;padding:0 16px">Enregistrer</button><span class="hint">Régime « ${T.regime(a.features.regime.regime)} » et niveau ${T.level(a.risk.level)} ajoutés automatiquement.</span></div>
        ${journal.length ? more(`Voir les ${journal.length} notes`, raw(journal.slice(-12).reverse().map((j) => `<div class="kv" style="align-items:flex-start"><span class="k" style="flex:1"><b style="color:var(--text)">${esc(j.title)}</b> <span class="tag">${esc(j.type)}</span><br/>${esc(j.note)}<br/><span class="dimc">${esc(fmt.datetime(j.ts))} · ${esc(T.regime(j.regime))} · ${esc(T.level(j.level))}</span></span></div>`).join(""))) : ""}
        ${rep.decisionsList.some((d) => d.resolved) ? more("Décisions résolues", raw(`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Date</th><th>Carte</th><th>Action</th><th class="r">p</th><th>Résultat</th><th class="r">R</th></tr></thead><tbody>${rep.decisionsList.filter((d) => d.resolved).slice(0, 15).map((d) => `<tr><td class="t">${esc(fmt.date(d.ts))}</td><td class="t">${esc(d.coin)} ${esc(d.side)} ${esc(T.setup(d.type))}</td><td class="t">${esc({ EXECUTE: "exécuté", SIMULATE: "simulé", IGNORE: "ignoré", VETO: "veto", GATE: "refusé", AUTO: "proposé" }[d.action] || d.action)}</td><td class="r">${Math.round(d.pWin * 100)} %</td><td class="t ${/WIN/.test(d.outcome) ? "pos" : "neg"}">${/WIN/.test(d.outcome) ? "gagné" : "perdu"}${/EXPIRED/.test(d.outcome) ? " (à l'échéance)" : ""}</td><td class="r">${isNum(d.realizedR) ? d.realizedR.toFixed(2) : "—"}</td></tr>`).join("")}</tbody></table></div>`)) : ""}
      </div>`);
    $("#j-add").addEventListener("click", () => { const title = $("#j-title").value.trim(), note = $("#j-note").value.trim(); if (!title && !note) return; AOS.store.push("journal", { id: AOS.util.uid(), ts: Date.now(), title, type: $("#j-type").value, note, regime: a.features.regime.regime, level: a.risk.level }); V.archive(a); });
    sum("archive", isNum(m?.alphaBTC) ? `alpha 30 j ${fmt.pct(m.alphaBTC, 1, true)}` : `${st.n} trades`);
  };

  // ---- VEILLE -----------------------------------------------------------------------------------------
  V.alerts = function (a) {
    const stored = AOS.store.list("alerts").slice(-12).reverse();
    const cur = a.alerts || [];
    const all = [...cur, ...stored.filter((s) => !cur.some((c) => c.id === s.id))].slice(0, 12);
    set($("#alerts-body"), all.length ? raw(all.map((x) => `<div class="alert card"><span class="stripe ${x.severity >= 3 ? "DANGER" : x.severity === 2 ? "WATCH" : "NORMAL"}"></span><div class="what">${esc(x.what)} <span class="dimc num" style="font-weight:400">${esc(fmt.datetime(x.ts))}</span></div><div class="why"><b>Pourquoi c'est important :</b> ${esc(x.why)}</div><div class="act"><b>${/^Aucune action/i.test(x.action) ? "Rien à faire" : "À faire"} :</b> ${esc(x.action)}</div></div>`).join("")) : html`<div class="empty">Rien à signaler. La veille n'alerte que pour : changement de régime, changement de niveau de risque, seuil de liquidation, funding anormal, stop traversé, opportunité à forte conviction, niveau de prix majeur, nouvelle position.</div>`);
    sum("alerts", all.length ? `${all.length} alerte${all.length > 1 ? "s" : ""}` : "calme");
  };

  // ---- RÉGLAGES ---------------------------------------------------------------------------------------
  V.settings = function () {
    const s = AOS.store.settings, fw = s.firewall, R = s.risk, W = s.weights;
    const n = (v) => (isNum(v) ? v : "");
    set($("#settings-body"), html`
      <div class="grid c2">
        <div class="card"><h3>Source de vérité</h3>
          <div class="field"><label>Wallet Hyperliquid (0x…)</label><input id="s-wallet" class="mono" value="${s.wallet}" spellcheck="false" autocapitalize="off"/></div>
          ${more("Synchronisation et veille", raw(`<div class="form c3"><div class="field"><label>Rafraîchissement (s)</label><input id="s-poll" inputmode="numeric" value="${Math.round(s.pollMs / 1000)}"/></div><div class="field"><label>Périmé après (s)</label><input id="s-stale" inputmode="numeric" value="${Math.round(s.staleAfterMs / 1000)}"/></div><div class="field"><label>WebSocket</label><select id="s-ws"><option value="1" ${s.useWebSocket ? "selected" : ""}>OUI</option><option value="0" ${!s.useWebSocket ? "selected" : ""}>NON</option></select></div></div><div class="form c2" style="margin-top:8px"><div class="field"><label>Synchro automatique</label><select id="s-auto"><option value="1" ${s.autoSync ? "selected" : ""}>OUI</option><option value="0" ${!s.autoSync ? "selected" : ""}>NON</option></select></div><div class="field"><label>Liste de suivi (narratifs)</label><input id="s-watch" value="${esc(s.watchlist.join(" "))}"/></div></div><div class="form c3" style="margin-top:8px"><div class="field"><label>Veille (07h30–20h30)</label><select id="s-w-on"><option value="1" ${s.watcher.enabled ? "selected" : ""}>OUI</option><option value="0" ${!s.watcher.enabled ? "selected" : ""}>NON</option></select></div><div class="field"><label>Début (h)</label><input id="s-w-start" inputmode="decimal" value="${s.watcher.startHour}"/></div><div class="field"><label>Fin (h)</label><input id="s-w-end" inputmode="decimal" value="${s.watcher.endHour}"/></div></div><div class="hint" style="margin-top:6px">La veille ne fonctionne que si l'onglet est ouvert (page statique, sans serveur). Les notifications du navigateur sont demandées à l'activation.</div>`), true)}
        </div>
        <div class="card"><h3>Pare-feu de capital <span class="tag">LOCAL SEULEMENT</span></h3>
          <div class="hint" style="margin-bottom:8px">Stocké uniquement dans ce navigateur. Jamais envoyé, jamais publié. Vide = inconnu. Le capital de trading plafonne les tailles ; sinon l'equity Hyperliquid est utilisée.</div>
          <div class="form c2">
            <div class="field"><label>Capital cœur (intouchable)</label><input id="s-fw-core" inputmode="decimal" value="${n(fw.coreCapital)}"/></div>
            <div class="field"><label>Capital d'investissement</label><input id="s-fw-inv" inputmode="decimal" value="${n(fw.investmentCapital)}"/></div>
            <div class="field"><label>Capital de trading</label><input id="s-fw-trade" inputmode="decimal" value="${n(fw.tradingCapital)}"/></div>
            <div class="field"><label>Marge tactique (exceptionnel)</label><input id="s-fw-tact" inputmode="decimal" value="${n(fw.tactical)}"/></div>
            <div class="field"><label>Charges mensuelles (crédits + vie)</label><input id="s-fw-obl" inputmode="decimal" value="${n(fw.monthlyObligations)}"/></div>
            <div class="field"><label>Dernière vérification</label><input id="s-fw-date" type="date" value="${fw.lastVerified || ""}"/></div>
          </div>
          ${more("Politique de risque et poids des agents", raw(`<div class="form c3"><div class="field"><label>Risque/trade (base)</label><input id="s-r-base" inputmode="decimal" value="${R.baseRiskPerTrade}"/></div><div class="field"><label>Risque/trade (max)</label><input id="s-r-max" inputmode="decimal" value="${R.maxRiskPerTrade}"/></div><div class="field"><label>Distance liq. min</label><input id="s-r-liq" inputmode="decimal" value="${R.minLiqDistance}"/></div><div class="field"><label>Coussin min</label><input id="s-r-buf" inputmode="decimal" value="${R.minBufferRatio}"/></div><div class="field"><label>Concentration max</label><input id="s-r-conc" inputmode="decimal" value="${R.maxConcentration}"/></div><div class="field"><label>Corrélation de stress</label><input id="s-r-corr" inputmode="decimal" value="${R.normalCorrStress}"/></div></div><div class="form c3" style="margin-top:8px">${["ORACLE", "EDGE", "FLOW", "ALLOCATOR", "ARCHIVE"].map((k) => `<div class="field"><label>${esc(T.agent(k).name)}</label><input id="s-w-${k}" inputmode="decimal" value="${W[k]}"/></div>`).join("")}</div>`))}
        </div>
      </div>
      <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button class="btn primary" id="s-save" style="flex:0 0 auto;padding:0 18px">Enregistrer et resynchroniser</button><button class="btn ghost" id="s-export" style="flex:0 0 auto;padding:0 14px">Exporter (JSON)</button><button class="btn danger ghost" id="s-clear" style="flex:0 0 auto;padding:0 14px">Effacer les données locales de ce wallet</button></div>`);
    sum("settings", s.wallet ? s.wallet.slice(0, 6) + "…" + s.wallet.slice(-4) : "aucun wallet");
  };

  AOS.views = Object.assign(AOS.views || {}, V);
})(typeof window !== "undefined" ? window : globalThis);
